version: '3.6'
services:
  web:
    build:
      context: .
    container_name: websockets
    network_mode: bridge
    restart: on-failure
    volumes:
      - ./code:/var/www/html
    environment:
      VIRTUAL_HOST: websockets.docker
